version: "2"

services:
  grafana:
    image: grafana/grafana:5.2.2
    environment: 
      GF_SERVER_ROOT_URL: http://localhost:3000
      GF_SECURITY_ADMIN_PASSWORD: 123456
    ports:
      - 3000:3000
    user: "472"